server:
  port: 8081
  #disbale as client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/apigateway
    username: root
    password: Harry@2020
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
