server:
  port: 8081
  #disbale as client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/

