server:
  port: 8082
  #disbale as client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/